// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTavYxr-9fD3nDZuGdzUZc1kokwM29EA',
    appId: '1:77358190948:android:02f7f8dc7136038cac2a71',
    messagingSenderId: '77358190948',
    projectId: 'chat-56afa',
    storageBucket: 'chat-56afa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_T8KK92laMgpJLjaAaTPzZ6hhyLMcsM',
    appId: '1:77358190948:ios:e6d68747f07e4eceac2a71',
    messagingSenderId: '77358190948',
    projectId: 'chat-56afa',
    storageBucket: 'chat-56afa.appspot.com',
    androidClientId: '77358190948-94u8qhgco0onmr8rp4qgia30pe43frj7.apps.googleusercontent.com',
    iosClientId: '77358190948-2o95qlfa4uq8ocp2u1ultstkqb53pn9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatup',
  );
}
